# Generated by Django 3.1.7 on 2021-04-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='company_name',
        ),
    ]
